server:
  port: 14611
spring:
  application:
    name: server-web-consumer
  main:
    allow-bean-definition-overriding: true
dubbo:
  application:
    name: server-web-consumer
  scan:
    base-packages: com.ant
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos

  protocol:
    name: dubbo
    port: 15611
  consumer:
    group: product-group
