server:
  port: 10510
  tomcat:
    basedir: target/tomcat
    accesslog:
      enabled: true
spring:
  thymeleaf:
    cache: false
  application:
    name: server-web-gateway
    main:
      allow-bean-definition-overriding: true

application:
  message: Hello Ant

dubbo:
  application:
    name: server-web-gateway
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
  scan:
    base-packages: com.ant
  protocol:
    name: dubbo
    port: 10510
  consumer:
    group: product-group




