server:
  port: 7081

spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .html
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    suffix: .html
    template-loader-path: /WEB-INF/pages/

application:
  message: Hello Ant

